# Generated by Django 4.2.20 on 2025-07-25 00:06

# Django
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("place_order", "Can place an order"),
                    ("manage_store", "Can manage the store"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DeliverySystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "friendly_name",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Friendly Name",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evesolarsystem",
                        verbose_name="Solar System",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ForSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=4096, verbose_name="Description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        limit_choices_to={"published": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                        verbose_name="EVE Type",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deposit per unit",
                        max_digits=15,
                        verbose_name="Deposit",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit",
                        max_digits=15,
                        verbose_name="Price per unit",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, max_length=4096, verbose_name="Notes"),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        limit_choices_to={"published": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                        verbose_name="EVE Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Purchaser",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=4096, verbose_name="Description"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Pending"),
                            (20, "Awaiting Deposit"),
                            (30, "Building Parts"),
                            (35, "Building Hull"),
                            (40, "Contract Up"),
                            (50, "Delivered"),
                            (60, "Rejected"),
                        ],
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount paid",
                        max_digits=25,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "deliverysystem",
                    models.ForeignKey(
                        default=30000142,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evesolarsystem",
                        verbose_name="Delivery System",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Deposit required per unit",
                        max_digits=25,
                        verbose_name="Deposit required per unit",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "totalcost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total Order cost",
                        max_digits=25,
                        verbose_name="Total Order cost",
                    ),
                ),
                (
                    "on_behalf_of",
                    models.CharField(
                        blank=True,
                        help_text="EVE name of person you are ordering on behalf of",
                        max_length=37,
                        null=True,
                        verbose_name="On behalf of",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
