name: Tests

on:
  push:
    branches:
      - "main"

    tags-ignore:
      - "**"

  pull_request:
    branches:
      - "**"

    tags-ignore:
      - "**"

jobs:
  # pre-commit Checks
  devenv-test:
    name: Devenv Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any git hooks
        run: devenv test
